-- ==============================================
-- Script de Criação das Tabelas de Sincronização Ellox
-- Sistema: Farol v3.9.11
-- Data: 2025-10-05
-- ==============================================

-- 1. CRIAR TABELA DE LOGS DE SINCRONIZAÇÃO
-- ==============================================
CREATE TABLE LogTransp.F_ELLOX_SYNC_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SYNC_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    VESSEL_NAME VARCHAR2(200),
    VOYAGE_CODE VARCHAR2(100),
    TERMINAL VARCHAR2(200),
    STATUS VARCHAR2(50) NOT NULL, -- 'SUCCESS', 'NO_CHANGES', 'API_ERROR', 'AUTH_ERROR', 'SAVE_ERROR', 'ERROR', 'RETRY'
    CHANGES_DETECTED NUMBER DEFAULT 0,
    ERROR_MESSAGE CLOB,
    RETRY_ATTEMPT NUMBER DEFAULT 0,
    EXECUTION_TIME_MS NUMBER,
    USER_ID VARCHAR2(50) DEFAULT 'SYSTEM',
    FIELDS_CHANGED CLOB -- JSON string of changed fields
);

-- 2. CRIAR ÍNDICES PARA PERFORMANCE
-- ==============================================
CREATE INDEX LogTransp.IX_ELLOX_SYNC_LOGS_STATUS ON LogTransp.F_ELLOX_SYNC_LOGS (STATUS);
CREATE INDEX LogTransp.IX_ELLOX_SYNC_LOGS_VESSEL ON LogTransp.F_ELLOX_SYNC_LOGS (VESSEL_NAME);
CREATE INDEX LogTransp.IX_ELLOX_SYNC_LOGS_VOYAGE ON LogTransp.F_ELLOX_SYNC_LOGS (VOYAGE_CODE);
CREATE INDEX LogTransp.IX_ELLOX_SYNC_LOGS_TERMINAL ON LogTransp.F_ELLOX_SYNC_LOGS (TERMINAL);
CREATE INDEX LogTransp.IX_ELLOX_SYNC_LOGS_TIMESTAMP ON LogTransp.F_ELLOX_SYNC_LOGS (SYNC_TIMESTAMP DESC);

-- 3. CRIAR TABELA DE CONFIGURAÇÕES
-- ==============================================
CREATE TABLE LogTransp.F_ELLOX_SYNC_CONFIG (
    ID NUMBER DEFAULT 1 PRIMARY KEY, -- Always 1 for single config row
    SYNC_ENABLED NUMBER(1) DEFAULT 1, -- 1 for true, 0 for false
    SYNC_INTERVAL_MINUTES NUMBER DEFAULT 60, -- Interval in minutes
    MAX_RETRIES NUMBER DEFAULT 3, -- Max retry attempts for a failed sync
    LAST_EXECUTION TIMESTAMP,
    NEXT_EXECUTION TIMESTAMP,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4. INSERIR CONFIGURAÇÃO INICIAL
-- ==============================================
INSERT INTO LogTransp.F_ELLOX_SYNC_CONFIG (ID, SYNC_ENABLED, SYNC_INTERVAL_MINUTES, MAX_RETRIES, UPDATED_BY)
SELECT 1, 1, 60, 3, 'SYSTEM' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM LogTransp.F_ELLOX_SYNC_CONFIG WHERE ID = 1);

-- 5. COMMIT DAS ALTERAÇÕES
-- ==============================================
COMMIT;

-- 6. VERIFICAR CRIAÇÃO DAS TABELAS
-- ==============================================
SELECT 'F_ELLOX_SYNC_LOGS' as TABELA, COUNT(*) as REGISTROS FROM LogTransp.F_ELLOX_SYNC_LOGS
UNION ALL
SELECT 'F_ELLOX_SYNC_CONFIG' as TABELA, COUNT(*) as REGISTROS FROM LogTransp.F_ELLOX_SYNC_CONFIG;

-- 7. VERIFICAR ÍNDICES CRIADOS
-- ==============================================
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME 
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME IN ('F_ELLOX_SYNC_LOGS', 'F_ELLOX_SYNC_CONFIG')
ORDER BY TABLE_NAME, INDEX_NAME;

-- ==============================================
-- FIM DO SCRIPT
-- ==============================================
